- name: Creating a directory
  tags: directory
  file:
    path: ~/prometheus
    state: directory

- name: Installing the Prometheus
  tags: source
  unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.39.1/prometheus-2.39.1.linux-amd64.tar.gz
    dest: ~/prometheus
    remote_src: yes
    mode: 0777
    owner: root
    group: root

- name: Stopping the service of Prometheus
  service:
    name: prometheus
    state: stopped

- name: Adding the executables of Prometheus in path
  tags: executables
  shell: |
    cd ~/prometheus/prometheus*
    cp -r . /usr/local/bin/prometheus

- name: Copying the Prometheus service file
  tags: servicefile
  copy:
    src: prometheus.service
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: 777

- name: The httpd is started and enabled
  tags: serviceon
  service:
    name: prometheus
    state: restarted
    enabled: true

